apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.kubeconfigConfigMap.name }}
  namespace: {{ .Values.namespace.name }}
data: 
  yba-kubeconfig.yaml: {{ .Values.kubeconfigConfigMap.kubeconfig | quote }}
