apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.pullSecretConfigMap.name }}
  namespace: {{ .Values.namespace.name }}
data: 
  yugabyte-pull-secret.yaml: |
    apiVersion: v1
    kind: Secret
    metadata:
      name: {{ .Values.pullSecretConfigMap.pullSecretName }}
    data:
      .dockerconfigjson: {{ .Values.pullSecretConfigMap.pullSecret }}
    type: kubernetes.io/dockerconfigjson
