---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.loadGenerator.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.loadGenerator.name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.loadGenerator.name }}
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      restartPolicy: Always
      initContainers:
      - command:
        - /bin/sh
        - -exc
        - |
          echo "Init container pinging frontend: ${FRONTEND_ADDRESS}..."
          STATUSCODE=$(wget --server-response http://${FRONTEND_ADDRESS} 2>&1 | awk '/^  HTTP/{print $2}')
          if test $STATUSCODE -ne 200; then
              echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
              exit 1
          fi
        name: frontend-check
        image: busybox:latest
        env:
        - name: FRONTEND_ADDRESS
          value: {{ .Values.loadGenerator.frontendAddress | quote }}
      containers:
      - name: {{ .Values.loadGenerator.name }}
        image: {{ .Values.loadGenerator.containerImage }}
        imagePullPolicy: {{ .Values.loadGenerator.imagePullPolicy }}
        env:
        - name: FRONTEND_ADDRESS
          value: {{ .Values.loadGenerator.frontendAddress | quote}}
        - name: USERS
          value: {{ .Values.loadGenerator.users | quote }}
        resources:
          requests:
            cpu: 300m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
