{{ if .Values.namespace.create   }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  labels:
    {{ if .Values.namespace.labelForIstio }}
    istio-injection: enabled
    {{ end }}
{{ end }}