---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.payments.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.payments.name }}
    service: {{ .Values.payments.name }}
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: {{ .Values.payments.name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.payments.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.payments.name }}
spec:
  replicas: {{ .Values.payments.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.payments.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.payments.name }}
    spec:
      containers:
      - name: {{ .Values.payments.name }}
        image: {{ .Values.payments.containerImage }}
        imagePullPolicy: {{ .Values.payments.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.payments.containerPort }}
        env:
        - name: STRIPE_API_KEY
          valueFrom:
            secretKeyRef:
              name: payment-secret
              key: stripe-api-key

